{% set name = "TEtrimmer" %}
{% set version = "1.3.0" %}
{% set sha256 = "2d9f7c615fb289372ef8e005bf44d951467798928104605c2aff2b8ce93edf26" %} 
package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/qjiangzhao/TEtrimmer/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('tetrimmer', max_pin="x") }}

requirements:
  run:
    - python >=3.8,<3.11
    - numpy
    - perl 
    - r-base
    - blast
    - biopython
    - bedtools >=2.31.1
    - cd-hit
    - dataclasses
    - emboss
    - hmmer
    - iqtree
    - matplotlib-base
    - mafft
    - multiprocess
    - pandas
    - pfam_scan
    - plotly
    - pypdf2
    - regex
    - repeatmodeler  
    - repeatmasker
    - requests
    - samtools
    - scikit-learn
    - tk
    - urllib3
    - click
    - dill
    - joblib
    - nseg
    - recon
    - trf
    - ghostscript

test:
  commands:
    - TEtrimmer --help
    
about:
  home: https://github.com/qjiangzhao/TETrimmer.git
  license: GPL-3.0-only
  summary: "TETrimmer is designed to replace and assist TE manual curation."
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hangxue
    - qianjiangzhao